//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewRegistration", typeof(ResViewRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string CmdCheckEmail {
            get {
                return ResourceManager.GetString("CmdCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend E-Mail.
        /// </summary>
        public static string CmdResendEmailCheck {
            get {
                return ResourceManager.GetString("CmdResendEmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string CmdSave {
            get {
                return ResourceManager.GetString("CmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail für Login.
        /// </summary>
        public static string EntryEmailPlaceholder {
            get {
                return ResourceManager.GetString("EntryEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pflicht).
        /// </summary>
        public static string EntryFirstnamePlaceholder {
            get {
                return ResourceManager.GetString("EntryFirstnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        public static string EntryLastnamePlaceholder {
            get {
                return ResourceManager.GetString("EntryLastnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string LblFirstname {
            get {
                return ResourceManager.GetString("LblFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LblLastname {
            get {
                return ResourceManager.GetString("LblLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        public static string LblRepeatPassword {
            get {
                return ResourceManager.GetString("LblRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort anzeigen.
        /// </summary>
        public static string LblShowPassword {
            get {
                return ResourceManager.GetString("LblShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs E-Mail wurde bereits versandt. Bitte prüfen Sie Ihren Posteingang..
        /// </summary>
        public static string MsgBoxConfirmationEmailAlreadySent {
            get {
                return ResourceManager.GetString("MsgBoxConfirmationEmailAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs E-Mail wurde versandt. Bitte prüfen Sie Ihren Posteingang..
        /// </summary>
        public static string MsgBoxConfirmationEmailSent {
            get {
                return ResourceManager.GetString("MsgBoxConfirmationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string MsgBoxEmailHeader {
            get {
                return ResourceManager.GetString("MsgBoxEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider ist ein Problem aufgetreten!.
        /// </summary>
        public static string MsgBoxErrorOccurred {
            get {
                return ResourceManager.GetString("MsgBoxErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgBoxErrorOccurredHead {
            get {
                return ResourceManager.GetString("MsgBoxErrorOccurredHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Benutzer.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierung.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre E-Mail wurde erfolgreich bestätigt..
        /// </summary>
        public static string ToastEmailConfirmed {
            get {
                return ResourceManager.GetString("ToastEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs E-Mail wurde erneut versandt. Bitte prüfen Sie Ihren Posteingang. .
        /// </summary>
        public static string ToastEmailResent {
            get {
                return ResourceManager.GetString("ToastEmailResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail wurde nicht bestätigt. Bitte prüfen Sie Ihren Posteingang..
        /// </summary>
        public static string ToastNotConfirmedEmail {
            get {
                return ResourceManager.GetString("ToastNotConfirmedEmail", resourceCulture);
            }
        }
    }
}
