//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAppointments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAppointments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewAppointments", typeof(ResViewAppointments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Termine:.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast an diesem Tag keine Termine die wir dir anzeigen können..
        /// </summary>
        public static string LblNoAppointments {
            get {
                return ResourceManager.GetString("LblNoAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkäufer:.
        /// </summary>
        public static string LblStaff {
            get {
                return ResourceManager.GetString("LblStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wann:.
        /// </summary>
        public static string LblWhen {
            get {
                return ResourceManager.GetString("LblWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie den Termin wirklich löschen?.
        /// </summary>
        public static string MsgBoxDelete {
            get {
                return ResourceManager.GetString("MsgBoxDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string MsgBoxDeleteCaption {
            get {
                return ResourceManager.GetString("MsgBoxDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du Whatsapp öffnen?
        ///Hinweis: Das funktioniert nur wenn du WhatsApp installiert hast..
        /// </summary>
        public static string MsgBoxOpenWhatsApp {
            get {
                return ResourceManager.GetString("MsgBoxOpenWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string MsgBoxOpenWhatsAppCaption {
            get {
                return ResourceManager.GetString("MsgBoxOpenWhatsAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termine.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
