//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewEditUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewEditUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewEditUser", typeof(ResViewEditUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild ändern.
        /// </summary>
        public static string CmdEditPictureName {
            get {
                return ResourceManager.GetString("CmdEditPictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild ändern.
        /// </summary>
        public static string CmdEditPictureTooltip {
            get {
                return ResourceManager.GetString("CmdEditPictureTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichern.
        /// </summary>
        public static string CmdSaveName {
            get {
                return ResourceManager.GetString("CmdSaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten sichern.
        /// </summary>
        public static string CmdSaveTooltip {
            get {
                return ResourceManager.GetString("CmdSaveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überspringen.
        /// </summary>
        public static string CmdSkipName {
            get {
                return ResourceManager.GetString("CmdSkipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string LblCity {
            get {
                return ResourceManager.GetString("LblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string LblFirstName {
            get {
                return ResourceManager.GetString("LblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LblLastName {
            get {
                return ResourceManager.GetString("LblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional).
        /// </summary>
        public static string LblOptionalPlaceholder {
            get {
                return ResourceManager.GetString("LblOptionalPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postleitzahl.
        /// </summary>
        public static string LblPostalCode {
            get {
                return ResourceManager.GetString("LblPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du dir Ware zustellen lassen möchtest, dann kannst du hier deinen Namen und deine Adresse angeben..
        /// </summary>
        public static string LblRegistrationText {
            get {
                return ResourceManager.GetString("LblRegistrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Pflicht).
        /// </summary>
        public static string LblRequiredPlaceholder {
            get {
                return ResourceManager.GetString("LblRequiredPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straße.
        /// </summary>
        public static string LblStreet {
            get {
                return ResourceManager.GetString("LblStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdaten bearbeiten.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerdaten.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
