//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewLogin", typeof(ResViewLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string CmdDemo {
            get {
                return ResourceManager.GetString("CmdDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend E-Mail.
        /// </summary>
        public static string CmdResendEmailCheck {
            get {
                return ResourceManager.GetString("CmdResendEmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0043 1234 56789 eingeben).
        /// </summary>
        public static string EntryUserPhonePlaceholder {
            get {
                return ResourceManager.GetString("EntryUserPhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer:.
        /// </summary>
        public static string LblUserPhone {
            get {
                return ResourceManager.GetString("LblUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Mode nicht richtig konfiguriert!.
        /// </summary>
        public static string MsgBoxDemoError {
            get {
                return ResourceManager.GetString("MsgBoxDemoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string MsgBoxDemorErrorHead {
            get {
                return ResourceManager.GetString("MsgBoxDemorErrorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider ist ein Problem aufgetreten!.
        /// </summary>
        public static string MsgBoxError {
            get {
                return ResourceManager.GetString("MsgBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgBoxErrorHead {
            get {
                return ResourceManager.GetString("MsgBoxErrorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benuter ist durch den Admin gesperrt!.
        /// </summary>
        public static string MsgBoxUserLocked {
            get {
                return ResourceManager.GetString("MsgBoxUserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login nicht möglich.
        /// </summary>
        public static string MsgBoxUserLockedHead {
            get {
                return ResourceManager.GetString("MsgBoxUserLockedHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs E-Mail wurde erneut versandt. Bitte prüfe deinen Posteingang..
        /// </summary>
        public static string ToastConfirmationSent {
            get {
                return ResourceManager.GetString("ToastConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string ToastConfirmationSentHead {
            get {
                return ResourceManager.GetString("ToastConfirmationSentHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo-Account!.
        /// </summary>
        public static string ToastDemoUser {
            get {
                return ResourceManager.GetString("ToastDemoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login nicht möglich.
        /// </summary>
        public static string ToastDemoUserHead {
            get {
                return ResourceManager.GetString("ToastDemoUserHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account wurde noch nicht bestätigt.
        /// </summary>
        public static string ToastEmailUnconfirmed {
            get {
                return ResourceManager.GetString("ToastEmailUnconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login nicht möglich.
        /// </summary>
        public static string ToastEmailUnconfirmedHead {
            get {
                return ResourceManager.GetString("ToastEmailUnconfirmedHead", resourceCulture);
            }
        }
    }
}
