//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewPassword {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewPassword() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewPassword", typeof(ResViewPassword).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Passwort ....
        /// </summary>
        public static string BusyCheckingPassword {
            get {
                return ResourceManager.GetString("BusyCheckingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort anzeigen.
        /// </summary>
        public static string LblShowPassword {
            get {
                return ResourceManager.GetString("LblShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer oder Passwort ist falsch.
        /// </summary>
        public static string MsgBoxDataInvalid {
            get {
                return ResourceManager.GetString("MsgBoxDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MsgBoxDataInvalidHead {
            get {
                return ResourceManager.GetString("MsgBoxDataInvalidHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider ist ein Problem aufgetreten..
        /// </summary>
        public static string MsgBoxErrorOccurred {
            get {
                return ResourceManager.GetString("MsgBoxErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string MsgBoxErrorOccurredHead {
            get {
                return ResourceManager.GetString("MsgBoxErrorOccurredHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir wurde ein neues Passwort per SMS geschickt. .
        /// </summary>
        public static string MsgBoxNewPasswordSent {
            get {
                return ResourceManager.GetString("MsgBoxNewPasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string MsgBoxNewPasswordSentHead {
            get {
                return ResourceManager.GetString("MsgBoxNewPasswordSentHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User gesperrt!.
        /// </summary>
        public static string MsgBoxUserLocked {
            get {
                return ResourceManager.GetString("MsgBoxUserLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MsgBoxUserLockedHead {
            get {
                return ResourceManager.GetString("MsgBoxUserLockedHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort falsch!.
        /// </summary>
        public static string MsgBoxWrongPW {
            get {
                return ResourceManager.GetString("MsgBoxWrongPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string MsgBoxWrongPWHead {
            get {
                return ResourceManager.GetString("MsgBoxWrongPWHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zurück! 
        ///Geben Sie hier ihr Passwort ein:.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen bei Mein Schaufenster! 
        ///Geben Sie hier das Passwort ein, das wir ihnen per SMS geschickt haben..
        /// </summary>
        public static string SubTitleRegistration {
            get {
                return ResourceManager.GetString("SubTitleRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
