//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResView", typeof(ResView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wa.me/{0}.
        /// </summary>
        public static string CmdOpenWhatsAppUrl {
            get {
                return ResourceManager.GetString("CmdOpenWhatsAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wa.me/{0}?text={1}.
        /// </summary>
        public static string CmdOpenWhatsAppWithMessageUrl {
            get {
                return ResourceManager.GetString("CmdOpenWhatsAppWithMessageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Command_Back {
            get {
                return ResourceManager.GetString("Command_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Command_Continue {
            get {
                return ResourceManager.GetString("Command_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Command_Login {
            get {
                return ResourceManager.GetString("Command_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues PW senden.
        /// </summary>
        public static string Command_ResendPassword {
            get {
                return ResourceManager.GetString("Command_ResendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string LblClose {
            get {
                return ResourceManager.GetString("LblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich bin für den Videoanruf bereit..
        /// </summary>
        public static string LblReadyForVideoCall {
            get {
                return ResourceManager.GetString("LblReadyForVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Beratung wird über einen WhatsApp Videoanruf durchgeführt. Sobald du auf weiter drückst, wird WhatsApp geöffnet. Drücke dann bitte auf das Kamerasymbol oben rechts um den Videoanruf zu starten..
        /// </summary>
        public static string LblWhatsAppInfo {
            get {
                return ResourceManager.GetString("LblWhatsAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string MsgBox_CancelText {
            get {
                return ResourceManager.GetString("MsgBox_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gespeicherte Daten gehen verloren!
        ///Wollen Sie fortfahren?.
        /// </summary>
        public static string MsgBox_DataNotSaved {
            get {
                return ResourceManager.GetString("MsgBox_DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungsfehler.
        /// </summary>
        public static string MsgBox_HeaderNoInternet {
            get {
                return ResourceManager.GetString("MsgBox_HeaderNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihnen wurde ein Link zum zurücksetzen zugesand. Überprüfen Sie ihren Posteingang..
        /// </summary>
        public static string MsgBox_NewPasswordSent {
            get {
                return ResourceManager.GetString("MsgBox_NewPasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte überprüfen sie Ihre Internetverbindung..
        /// </summary>
        public static string MsgBox_NoInternet {
            get {
                return ResourceManager.GetString("MsgBox_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string MsgBox_NoText {
            get {
                return ResourceManager.GetString("MsgBox_NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string MsgBox_OkText {
            get {
                return ResourceManager.GetString("MsgBox_OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten konnten nicht gesichert werden..
        /// </summary>
        public static string MsgBox_SaveError {
            get {
                return ResourceManager.GetString("MsgBox_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten wurden erfolgreich gesichert..
        /// </summary>
        public static string MsgBox_SaveSuccess {
            get {
                return ResourceManager.GetString("MsgBox_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with server not possible!.
        /// </summary>
        public static string MsgBox_ServerFail {
            get {
                return ResourceManager.GetString("MsgBox_ServerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zu viele aktive Verbindungen, bitte versuchen Sie es später erneut!.
        /// </summary>
        public static string MsgBox_ServerMultiConnectionFail {
            get {
                return ResourceManager.GetString("MsgBox_ServerMultiConnectionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout connecting to server!.
        /// </summary>
        public static string MsgBox_ServerTimeout {
            get {
                return ResourceManager.GetString("MsgBox_ServerTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account invalid!.
        /// </summary>
        public static string MsgBox_ServerTokenFail {
            get {
                return ResourceManager.GetString("MsgBox_ServerTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string MsgBox_YesText {
            get {
                return ResourceManager.GetString("MsgBox_YesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Kamera. Möchten sie die Einstellungen öffnen?.
        /// </summary>
        public static string MsgBoxCameraAccess {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Kamera.
        /// </summary>
        public static string MsgBoxCameraAccessInfo {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benötigt Kamera.
        /// </summary>
        public static string MsgBoxCameraAccessInfoTitle {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string MsgBoxCameraAccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxCameraAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf das Dateisystem. Möchten sie die Einstellungen öffnen?.
        /// </summary>
        public static string MsgBoxFileAccess {
            get {
                return ResourceManager.GetString("MsgBoxFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf das Dateisystem.
        /// </summary>
        public static string MsgBoxFileAccessInfo {
            get {
                return ResourceManager.GetString("MsgBoxFileAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benötigt Dateisystem.
        /// </summary>
        public static string MsgBoxFileAccessInfoTitle {
            get {
                return ResourceManager.GetString("MsgBoxFileAccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string MsgBoxFileAccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxFileAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        public static string MsgBoxHeader_DataNotSaved {
            get {
                return ResourceManager.GetString("MsgBoxHeader_DataNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichern fehlgeschlagen.
        /// </summary>
        public static string MsgBoxHeader_SaveError {
            get {
                return ResourceManager.GetString("MsgBoxHeader_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichern.
        /// </summary>
        public static string MsgBoxHeader_SaveSuccess {
            get {
                return ResourceManager.GetString("MsgBoxHeader_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication error.
        /// </summary>
        public static string MsgBoxHeader_ServerRestError {
            get {
                return ResourceManager.GetString("MsgBoxHeader_ServerRestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Ortungsdienste. Möchten sie die Einstellungen öffnen?.
        /// </summary>
        public static string MsgBoxLocationAccess {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App benötigt Zugriff auf die Position.
        /// </summary>
        public static string MsgBoxLocationAccessInfo {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benötigt Position.
        /// </summary>
        public static string MsgBoxLocationAccessInfoTitle {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccessInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string MsgBoxLocationAccessTitle {
            get {
                return ResourceManager.GetString("MsgBoxLocationAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new version {0} available. You are using version {1}. 
        ///Do you want to update the application now?.
        /// </summary>
        public static string MsgBoxNewUpdate {
            get {
                return ResourceManager.GetString("MsgBoxNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurs updating the application. Please contact your support. 
        ///Applikation can not be launched!.
        /// </summary>
        public static string MsgBoxNewUpdateError {
            get {
                return ResourceManager.GetString("MsgBoxNewUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is new version {0} available. You are using version {1}. This is required update. 
        ///Press Ok to begin updating the application..
        /// </summary>
        public static string MsgBoxNewUpdateMandatory {
            get {
                return ResourceManager.GetString("MsgBoxNewUpdateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string MsgBoxTitleUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgBoxTitleUpdateAvailable", resourceCulture);
            }
        }
    }
}
