//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewMain", typeof(ResViewMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig!.
        /// </summary>
        public static string BusyContentFinished {
            get {
                return ResourceManager.GetString("BusyContentFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade {0}%.
        /// </summary>
        public static string BusyContentLoading {
            get {
                return ResourceManager.GetString("BusyContentLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string CmdQuit {
            get {
                return ResourceManager.GetString("CmdQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung erteilen.
        /// </summary>
        public static string CmdRequestPermission {
            get {
                return ResourceManager.GetString("CmdRequestPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail senden.
        /// </summary>
        public static string CmdSendEmail {
            get {
                return ResourceManager.GetString("CmdSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail an biss@fotec.at senden.
        /// </summary>
        public static string CmdSendEmailTooltip {
            get {
                return ResourceManager.GetString("CmdSendEmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubMenu.
        /// </summary>
        public static string CmdSubMenu {
            get {
                return ResourceManager.GetString("CmdSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusyTest.
        /// </summary>
        public static string CmdTestIsBusy {
            get {
                return ResourceManager.GetString("CmdTestIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viel Spaß beim Testen der Basis Möglichkeiten!.
        /// </summary>
        public static string LblBasic {
            get {
                return ResourceManager.GetString("LblBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlossen.
        /// </summary>
        public static string LbLClose {
            get {
                return ResourceManager.GetString("LbLClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beratungstermin:.
        /// </summary>
        public static string LblConsulting {
            get {
                return ResourceManager.GetString("LblConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfügbar.
        /// </summary>
        public static string LblConsultingAvailable {
            get {
                return ResourceManager.GetString("LblConsultingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagen.
        /// </summary>
        public static string LblDays {
            get {
                return ResourceManager.GetString("LblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis DEMO App der FOTEC Forschungs- und Technologietransfer GMBH des Bereichs Innovative Software Systems (BISS).
        /// </summary>
        public static string LblDemoApp {
            get {
                return ResourceManager.GetString("LblDemoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string LblDueIn {
            get {
                return ResourceManager.GetString("LblDueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die FOTEC ist das Forschungsunternehmen der Fachhochschule Wiener Neustadt.
        /// </summary>
        public static string LblFotec {
            get {
                return ResourceManager.GetString("LblFotec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        public static string LblHint {
            get {
                return ResourceManager.GetString("LblHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunden.
        /// </summary>
        public static string LblHours {
            get {
                return ResourceManager.GetString("LblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos per E-Mail unter biss@fotec.at.
        /// </summary>
        public static string LblInfo {
            get {
                return ResourceManager.GetString("LblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartung.
        /// </summary>
        public static string LblMaintenance {
            get {
                return ResourceManager.GetString("LblMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuten.
        /// </summary>
        public static string LblMinutes {
            get {
                return ResourceManager.GetString("LblMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Position kann nicht abgerufen werden. Bitte überprüfe ob du GPS aktiviert hast!.
        /// </summary>
        public static string LblNoAccess {
            get {
                return ResourceManager.GetString("LblNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn du GPS aktiviert hast, überprüfe bitte ob die App die notwendigen Berechtigungen hat. Das kannst du auch mit dem Button machen:.
        /// </summary>
        public static string LblNoAccessPermissions {
            get {
                return ResourceManager.GetString("LblNoAccessPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Geschäft hat derzeit leider keine freien Beratungstermine..
        /// </summary>
        public static string LblNoConsulting {
            get {
                return ResourceManager.GetString("LblNoConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geöffnet.
        /// </summary>
        public static string LbLOpen {
            get {
                return ResourceManager.GetString("LbLOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnungszeiten:.
        /// </summary>
        public static string LblOpeningHours {
            get {
                return ResourceManager.GetString("LblOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Geschäft hat derzeit nicht geöffnet. 
        ///Willst du trotzdem anrufen?.
        /// </summary>
        public static string LblOutsideOpeningHours {
            get {
                return ResourceManager.GetString("LblOutsideOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezahlmöglichkeiten:.
        /// </summary>
        public static string LblPaymentOptions {
            get {
                return ResourceManager.GetString("LblPaymentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie:.
        /// </summary>
        public static string LblProducts {
            get {
                return ResourceManager.GetString("LblProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin vereinbaren.
        /// </summary>
        public static string LblScheduleAppointment {
            get {
                return ResourceManager.GetString("LblScheduleAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gleich.
        /// </summary>
        public static string LblSoon {
            get {
                return ResourceManager.GetString("LblSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In diesem Bereich suchen.
        /// </summary>
        public static string LblUpdateSearch {
            get {
                return ResourceManager.GetString("LblUpdateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Geschäft ist derzeit nicht für eine Videoberatung verfügbar. 
        ///Willst du es trotzdem versuchen?
        ///Hinweis: Das funktioniert nur wenn du WhatsApp installiert hast..
        /// </summary>
        public static string LblWhatsAppNotAvailable {
            get {
                return ResourceManager.GetString("LblWhatsAppNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo!.
        /// </summary>
        public static string MsgBoxHello {
            get {
                return ResourceManager.GetString("MsgBoxHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gab ein Problem beim Abruf der Geschäftsdaten. Bitte versuche es später nocheinmal..
        /// </summary>
        public static string MsgBoxLoadError {
            get {
                return ResourceManager.GetString("MsgBoxLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        public static string MsgBoxLoadErrorCaption {
            get {
                return ResourceManager.GetString("MsgBoxLoadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du Whatsapp öffnen?
        ///Hinweis: Das funktioniert nur wenn du WhatsApp installiert hast..
        /// </summary>
        public static string MsgBoxOpenWhatsApp {
            get {
                return ResourceManager.GetString("MsgBoxOpenWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string MsgBoxOpenWhatsAppCaption {
            get {
                return ResourceManager.GetString("MsgBoxOpenWhatsAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Geschäft ist derzeit nicht für eine Videoberatung verfügbar..
        /// </summary>
        public static string MsgBoxWhatsAppContactUnavailable {
            get {
                return ResourceManager.GetString("MsgBoxWhatsAppContactUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videoberatung nicht verfügbar.
        /// </summary>
        public static string MsgBoxWhatsAppContactUnavailableTitle {
            get {
                return ResourceManager.GetString("MsgBoxWhatsAppContactUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäftsname.
        /// </summary>
        public static string PlaceholderSearch {
            get {
                return ResourceManager.GetString("PlaceholderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOTEC Demo App.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
