//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewDeveloperInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewDeveloperInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewDeveloperInfo", typeof(ResViewDeveloperInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig!.
        /// </summary>
        public static string BusyCompleteText {
            get {
                return ResourceManager.GetString("BusyCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade {0}%.
        /// </summary>
        public static string BusyLoadingText {
            get {
                return ResourceManager.GetString("BusyLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusyTest.
        /// </summary>
        public static string CmdBusyTest {
            get {
                return ResourceManager.GetString("CmdBusyTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string CmdPing {
            get {
                return ResourceManager.GetString("CmdPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppCenter (Push) Id:.
        /// </summary>
        public static string LblAppCenterId {
            get {
                return ResourceManager.GetString("LblAppCenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Sprache:.
        /// </summary>
        public static string LblAppLanguage {
            get {
                return ResourceManager.GetString("LblAppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandbreite(n):.
        /// </summary>
        public static string LblBandwith {
            get {
                return ResourceManager.GetString("LblBandwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungsart(en):.
        /// </summary>
        public static string LblConnectionTypes {
            get {
                return ResourceManager.GetString("LblConnectionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verbunden.
        /// </summary>
        public static string LblConnectivityConnected {
            get {
                return ResourceManager.GetString("LblConnectivityConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICHT verbunden.
        /// </summary>
        public static string LblConnectivityNotConnected {
            get {
                return ResourceManager.GetString("LblConnectivityNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Id:.
        /// </summary>
        public static string LblDeviceHardwareId {
            get {
                return ResourceManager.GetString("LblDeviceHardwareId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräteart:.
        /// </summary>
        public static string LblDeviceIdiom {
            get {
                return ResourceManager.GetString("LblDeviceIdiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätesprache:.
        /// </summary>
        public static string LblDeviceLanguage {
            get {
                return ResourceManager.GetString("LblDeviceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betriebssystem:.
        /// </summary>
        public static string LblDeviceOs {
            get {
                return ResourceManager.GetString("LblDeviceOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plattform:.
        /// </summary>
        public static string LblDevicePlatform {
            get {
                return ResourceManager.GetString("LblDevicePlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätetyp:.
        /// </summary>
        public static string LblDeviceType {
            get {
                return ResourceManager.GetString("LblDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet:.
        /// </summary>
        public static string LblInternet {
            get {
                return ResourceManager.GetString("LblInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST Url:.
        /// </summary>
        public static string LblRestUrl {
            get {
                return ResourceManager.GetString("LblRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via Email senden.
        /// </summary>
        public static string LblSendEmail {
            get {
                return ResourceManager.GetString("LblSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalR Endpoint:.
        /// </summary>
        public static string LblSignalRBaseUrl {
            get {
                return ResourceManager.GetString("LblSignalRBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgBoxEmailErrorHeader {
            get {
                return ResourceManager.GetString("MsgBoxEmailErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Senden der Email ist ein Fehler aufgetreten..
        /// </summary>
        public static string MsgBoxEmailErrorText {
            get {
                return ResourceManager.GetString("MsgBoxEmailErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infos zum Gerät.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwicklerinformationen.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Ok!.
        /// </summary>
        public static string ToastPing {
            get {
                return ResourceManager.GetString("ToastPing", resourceCulture);
            }
        }
    }
}
