//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewUser", typeof(ResViewUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ändern.
        /// </summary>
        public static string CmdChangePassword {
            get {
                return ResourceManager.GetString("CmdChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten ändern.
        /// </summary>
        public static string CmdChangeUserData {
            get {
                return ResourceManager.GetString("CmdChangeUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account löschen.
        /// </summary>
        public static string CmdDeleteAccount {
            get {
                return ResourceManager.GetString("CmdDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string CmdLogout {
            get {
                return ResourceManager.GetString("CmdLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Geräte.
        /// </summary>
        public static string CmdUserDevices {
            get {
                return ResourceManager.GetString("CmdUserDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willst du deinen Account wirklich löschen?.
        /// </summary>
        public static string MsgBoxDeleteAccount {
            get {
                return ResourceManager.GetString("MsgBoxDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirklich löschen?.
        /// </summary>
        public static string MsgBoxDeleteAccountCaption {
            get {
                return ResourceManager.GetString("MsgBoxDeleteAccountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten können gerade nicht geladen werden! 
        ///Bitte prüfen Sie Ihre Internetverbindung.
        /// </summary>
        public static string MsgBoxOffline {
            get {
                return ResourceManager.GetString("MsgBoxOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Account.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Account.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
